### ISSUE TITLE
Player crash bug when playing _really_ fast. Probably dont happen in real life, but it should be investigated.

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#140]
1. Add temponode at line 10.
2. Add temponode at line 5. Make it have a value of approx 10000 or so.
3. Play block. When the block starts playing at line 0 for the first time, this happens:

$1 = (struct PEventQueue *) 0x0
(gdb) bt
#0  0x000000000046eeb1 in GetPEQelement () at common/PEQmempool.c:63
#1  0x000000000046ed23 in PlayerNewRealline (peq=0x338fc00, doit=1) at common/PEQrealline.c:140
#2  0x000000000046e477 in PlayerTask (reltime=64) at common/player.c:114
#3  0x00000000005daada in Mixer::RT_thread (this=0x2627660) at audio/Mixer.cpp:517
#4  0x00000000005dac29 in Mixer::RT_rjack_thread (arg=<optimized out>) at audio/Mixer.cpp:553
#5  0x0000003b564163fd in Jack::JackClient::Execute (this=0x2a59a40) at ../common/JackClient.cpp:565
#6  0x0000003b56435910 in Jack::JackPosixThread::ThreadHandler (arg=0x2a59bb0) at ../posix/JackPosixThread.cpp:59
#7  0x0000003b49c07d14 in start_thread () from /lib64/libpthread.so.0
#8  0x0000003b494f168d in clone () from /lib64/libc.so.6
(gdb)

**Comment by kmatheussen** [comment]
Fixed
