### ISSUE TITLE
race issues with g_num_allocated_click_plugins

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#429]
```
path: -sounds/243749__unfa__metronome-1khz-weak-pulse.flac-, loading-path: -/home/kjetil/radium/bin/mod_song_template.rad-
Header id says it is not an xi instrument: "fLaC".
Num channels: 1
New SoundProducer. Inputs: 0, Ouptuts: 2. plugin->type->name: Click
==2037==WARNING: AddressSanitizer failed to allocate 0xffffffff80000108 bytes
==2037==AddressSanitizer's allocator is terminating the process instead of returning 0
==2037==If you don't like this behavior set allocator_may_return_null=1
==2037==AddressSanitizer CHECK failed: ../../../../libsanitizer/sanitizer_common/sanitizer_allocator.cc:147 "((0)) != (0)" (0x0, 0x0)
    #0 0x7ffff6f0c981  (/lib64/libasan.so.2+0xa0981)
    #1 0x7ffff6f11933 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/lib64/libasan.so.2+0xa5933)
    #2 0x7ffff6e89845  (/lib64/libasan.so.2+0x1d845)
    #3 0x7ffff6f0fbb5  (/lib64/libasan.so.2+0xa3bb5)
    #4 0x7ffff6e8ef6d  (/lib64/libasan.so.2+0x22f6d)
    #5 0x7ffff6e8fe37  (/lib64/libasan.so.2+0x23e37)
    #6 0x7ffff6f04ad5 in __interceptor_calloc (/lib64/libasan.so.2+0x98ad5)
    #7 0x901916 in calloc_one_arg common/validatemem.cpp:491
    #8 0x901a2e in V_alloc common/validatemem.cpp:386
    #9 0x901d08 in V_calloc__ common/validatemem.cpp:495
    #10 0xc6b4ce in Mixer::add_SoundProducer(SoundProducer*) audio/Mixer.cpp:410
    #11 0xc6b4ce in MIXER_add_SoundProducer(SoundProducer*) audio/Mixer.cpp:994
    #12 0xc23fcd in SoundProducer::SoundProducer(SoundPlugin*, int, Buses) audio/SoundProducer.cpp:506
    #13 0xc23fcd in SP_create(SoundPlugin*, Buses) audio/SoundProducer.cpp:1058
    #14 0xc7f53b in CHIP_create_from_state mixergui/QM_chip.cpp:1349
    #15 0xc879f0 in MW_create_chips_from_state mixergui/QM_MixerWidget.cpp:1485
    #16 0xc8da23 in MW_create_from_state mixergui/QM_MixerWidget.cpp:1568
    #17 0x935cf1 in DLoadSong common/disk_song.c:169
    #18 0x937bb0 in DLoadRoot common/disk_root.c:181
    #19 0x939de9 in Load common/disk_load.c:168
    #20 0x939eeb in Load_CurrPos_org common/disk_load.c:227
    #21 0x93a1b7 in LoadSong_CurrPos common/disk_load.c:265
    #22 0xa520a6 in loadSong api/api_various.c:460
```

**Comment by kmatheussen** [comment]
Think this has been fixed.
